matrix:
  include:
    - language: python
      python:
        - "3.7"
      before_install: cd sk_processor
      install:
        - pip install -r requirements.txt
      before_script: cd src
      script:
        - pip install -e .
        - py.test -v

    - language: java
      os: linux
      jdk: openjdk13
      before_script: cd ggp
      script:
        - ./gradlew clean test

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/